apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ioms-sit # or ioms-uat
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi