environment:
  NODE_ENV: sit

image:
  repository: 703255197920.dkr.ecr.ap-southeast-1.amazonaws.com/obs-dev/sit
  name: ioms-web-sit 
  tag: "sit-de1dfba7"
  pullPolicy: Always

# Number of replicas
replicaCount: 3

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
      - host: develop1.obs-dev.pssobs.net
        paths:
          - path: /
            pathType: Prefix

# Resource configuration
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

deployment:
  imagePullSecrets:
  - name: ecr-secret