environment:
  NODE_ENV: sit

image:
  repository: 703255197920.dkr.ecr.ap-southeast-1.amazonaws.com/obs-dev/sit
  name: ioms-web-sit 
  tag: "sit-de1dfba7"
  pullPolicy: Always

# Number of replicas
replicaCount: 3

service:
  type: ClusterIP
  port: 80
  targetPort: 5173

ingress:
  enabled: true
  host: develop1.obs-dev.pssobs.net
  className: nginx

# # Service configuration
# service: 
#   port: 80
#   targetPort: 5173
#   type: LoadBalancer

# # Ingress configuration
# ingress:
#   enabled: true
#   className: alb
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:703255197920:certificate/4e3058f2-469f-4d97-847b-7e5173141958da
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
#     alb.ingress.kubernetes.io/healthcheck-path: "/"
#     alb.ingress.kubernetes.io/success-codes: "200-399"

#   hosts:
#     - host: develop1.obs-dev.pssobs.net
#       paths:
#         - path: /
#           pathType: Prefix

# Resource configuration
resources:
  limits:
    cpu: 500m    
    memory: 512Mi 
  requests:
    cpu: 250m    
    memory: 256Mi 

livenessProbe:
  httpGet:
    path: /
    port: 5173
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: 5173
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

deployment:
  imagePullSecrets:
  - name: ecr-secret