apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ioms-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ioms-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ioms-web
    spec:
      containers:
        - name: ioms-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.environment }}
          env:
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          